### ISSUE TITLE
'undefined' as a css property

### ISSUE THREAD

**Issue by alexanbj** [emotion-js/emotion#1119]
- `emotion` version: 10.0.5
- `react` version: 16.5.2

**Relevant code:** 
```javascript
function tablet(...args) {
  return css`
    @media (min-width: 100px) {
      ${css(...args)};
    }
  `;
}

const H2 = styled('h2')`
  ${tablet`color: red;`}
`;
```

**What you did:** Upgraded from Emotion 9 to Emotion 10

**What happened:** I get `undefined`as a (vendor prefixed!) css property in every one of my media queries.

<img width="201" alt="screenshot 2018-12-17 at 10 35 49" src="https://user-images.githubusercontent.com/81577/50078542-8e6b9880-01e7-11e9-91ad-19168a0bb6c6.png">

**Reproduction:** https://codesandbox.io/s/llm7j6rnp7

**Problem description:** I've upgraded from Emotion 9 to Emotion 10, and it's mostly been a smooth ride. Since I am doing SSR I especially appreciate how much simpler it is now. The only thing that I haven't been able to work out is some quirkiness with the way I do media queries (which works fine in version 9). In version 10 I get the `undefined` CSS property. I am not sure if this is due to an API change or if it is actually a bug.

**Suggested solution:** N/A

**Comment by Andarist** [comment]
Fixed here - https://codesandbox.io/s/mm29n1wxlx

I understand though it was not obvious how to use it correctly here, I think our mention of `@emotion/css/macro` [here](https://emotion.sh/docs/babel-macros) is confusing - when using it you still have to use our jsx pragma, because vanilla jsx doesn't know the css prop. Should we just improve docs or is there a way to fix it in the macro (I think there is not, because of this "The one exception to this is @emotion/core, @emotion/core doesn’t have a Babel Macro because Babel Macros doesn’t support macros for custom JSX pragmas.") cc @mitchellhamilton

**Comment by alexanbj** [comment]
@Andarist oh sorry, you're right. CRA and Emotion 10 was a bit confusing. But that's not why I opened this issue. My problem is that the generated CSS has all these undefines in it. This still happens in your fixed version with the custom pragma.

```css
  @media (min-width:100px) {
    .css-6y732l-test {
      color:red;
      -webkit-undefined;
      -ms-flex-undefined;
      undefined;
    }
  }
```

**Comment by Andarist** [comment]
After thinking a little bit about this - did it work in emotion@9? Could u prepare a sandbox based on emotion@9?

**Comment by alexanbj** [comment]
Sure thing! Here is the same code working in Emotion 9 https://codesandbox.io/s/r7nlppzmnq

**Comment by alexanbj** [comment]
If I remember correctly, I based my code on this example from the [styled-components documentation](https://www.styled-components.com/docs/advanced#media-templates).

**Comment by jwvance** [comment]
I had this issue as well, but in my case I resolved it by [https://github.com/emotion-js/emotion/issues/1354#issuecomment-537249934](fixing a bad ts/babel setup.)
