### ISSUE TITLE
React warning: Prop `className` did not match.

### ISSUE THREAD

**Issue by fsaheli** [emotion-js/emotion#1709]
**Current behavior:**

When using SSR and in dev mode, the classname generated on the server doesn't match what's on the client.

I think I've narrowed it down to an issue involving sourcemaps. 

In https://github.com/emotion-js/emotion/blob/117c6e42687cdcb773153f7400c5a430f228aa73/packages/serialize/src/index.js#L387 it seems the code is attempting to extract the sourcemap string in the style:

```
  if (process.env.NODE_ENV !== 'production') {
    styles = styles.replace(sourceMapPattern, match => {
      sourceMap = match
      return ''
    })
  }
```

The particular elements that gives rise to this bug seem to have multiple sourcemaps. This is the style before the `replace` (I've abbreviated the base64 string itself):

```
color: #1a1a1a;
  font-weight: bold;
  margin: 0;
  padding: 0;
 color:;font-size:32px;line-height:1.15;margin-bottom:4px;/*# sourceMappingURL=data:application/json;charset=utf-8;base64,ey...19 */label:ColoredCardHeading;color:#BB2F89;hyphens:auto;/*# sourceMappingURL=data:application/json;charset=utf-8;base64,ey...19 */
```

And this is the style after replace:

```
color: #1a1a1a;
  font-weight: bold;
  margin: 0;
  padding: 0;
 color:;font-size:32px;line-height:1.15;margin-bottom:4px;label:ColoredCardHeading;color:#BB2F89;hyphens:auto;/*# sourceMappingURL=data:application/json;charset=utf-8;base64,ey...19
```

This particular component is created by extending another component in another file:

```
(file1.js)
import Component2 from "file2.js";
const Component1 = styled(Component2).`...`

(file2.js)
const Component3 = ...
const Component2 = styled(Component3)`...`
export default Component2
```

The base64 encoded strings in the styles above point to `file1` and `file2` respectively. So I suspect either there is a bug in sourcemap generation which creates two instances of sourcemap in the same style string, or a problem with the replace mechanism that extracts one and not the other.

The actual mismatch happens because the server generated sourcemap has `"sources": ["file1.js"]` in the base64 encoded json sourcemap, while on the client this is fully qualified: `"sources": ["/Users/.../file1.js"]`

**To reproduce:**

I'd be happy to create a repo to demo this, it will take me some time though due to SSR and the use of `extractCritical`.

**Expected behavior:**

Using the basic apis for `styled` should not create mismatched classname on client & server.

**Environment information:**

- `react` version: 16.6.0
- `@emotion` version: 10.0.27

**Comment by Andarist** [comment]
> So I suspect either there is a bug in sourcemap generation which creates two instances of sourcemap in the same style string

I think this might happen when you compose multiple styles into 1 - in such a case we don't prune other source maps, but rather leave all of them and later only search for one using that regex. So this alone is not immediately a sign of a bug.

I would love to see a repro case because it would help us tremendously to locate the bug, without it we can only guess stuff and waste way more time on the issue than when having a repro case.

Thank you for the report though! I'm going to wait for that repro case.

**Comment by Andarist** [comment]
Are you maybe using a wrapper around emotion - like for example Theme UI? Are all browsers affected?

**Comment by fsaheli** [comment]
@Andarist We are not using a wrapper, and yes, all browsers are affected. I have been digging into this though, and the error definitely is what I wrote above, the mismatch between sourcemaps: the sourcemap string in the server has a `sources` attribute that is unqualified + a `sourceRoot`(`"sourceRoot":"/Users/mine/code/homepage/src/components", "sources":["Heading.js"]`). On the client there is a fully qualified route in `sources` and no `sourceRoot` (`"sources":["/Users/mine/code/homepage/src/components/Heading.js"]`)

Do you think this might be caused by our webpack/babel config? I tried to disable all options for generating sourcemaps but this sourcemap is still being generated. I'd appreciate any suggestions!

**Comment by Andarist** [comment]
I would check if you have multiple babel-plugin-emotion in your node_modules maybe. Have you passed `sourceMap: false` to our plugin? If yes - maybe you have some pretranspiled files in your node_modules? Something already transpiled using our plugin and you are just consuming it as is?

> Do you think this might be caused by our webpack/babel config?

The mismatch - not sure, I'm just rather surprised by a report that you have disabled source maps and they are still there, so that might be related to some configuration problems.

Would love to see a runnable repro case - that way I could tell you rather quickly what's going on. Right now I'm just shooting blindly without it.

**Comment by fsaheli** [comment]
@Andarist I was wrong, passing `sourceMap: false` to the emotion babel plugin fixes the issue. I managed to create a repo, here it is: https://github.com/fsaheli/emotion-classname-mismatch Let me know when you get the chance to take a look. Thanks!

**Comment by Andarist** [comment]
I'm not sure why exactly but your SSR and client-side have different settings for Babel. Maybe it's because you are using babel-node? 

The problem is that we receive different arguments from Babel. We read "generatorsOpts" and filename related properties are set to:
```js
const serverGeneratorOpts = {
  sourceFileName: 'Headings.js',
  sourceRoot: '/emotion-classname-mismatch/src/components'
}

const clientGeneratorOpts = {
  sourceFileName: '/emotion-classname-mismatch/src/components/Headings.js',
  sourceRoot: undefined
}
```

When I've tweaked how those are passed to the SourceMapGenerator it has fixed the issue. I'm not sure though if we should "fix" this on our side as I'm not entirely sure how this info is utilized by the SourceMapGenerator.

**Comment by fsaheli** [comment]
I see. Thanks for looking into it. It doesn't sound like this has anything to do with Emotion per se, so I'm going to close the issue. I mean a possible solution to the specific mismatch issue could be to generate the hash based on a style string without any sourcemaps, but I've fixed our issue by disabling sourcemaps altogether, and when I have time I'll debug the babel config mismatch...

**Comment by Andarist** [comment]
@fsaheli funny thing - this most likely got fixed by accident on the `next` branch. The goal of the change was to give more accurate source maps to the browser for composed styles and to make this happen we had to add `g` flag to that `sourceMapPattern`:
https://github.com/emotion-js/emotion/blob/d950d7d3a2d0a4c77d9037c0dbeae9d0b24e6577/packages/serialize/src/index.js#L335

I believe this accidentally fixed your problem. I encourage you to migrate to v11 (available on npm) anyway, even if you have already worked around your problem.

**Comment by shobhitsharma** [comment]
@Andarist It still persist for Firefox and Safari, in chrome works fine.

**Comment by max-pod** [comment]
@Andarist similar problem in Firefox

**Comment by Andarist** [comment]
@max-pod which version of Emotion are you using?

**Comment by gmarinov** [comment]
@Andarist same. latest.
